# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# format = '| $directory'

# [os]
# format = "[andya]($style) @ [($name )]($style)"
# style = "bold blue"
# disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[cmd_duration]
disabled = true

[git_branch]
disabled = true

[git_state]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[c]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[rust]
disabled = true
