[[keymaps]]
command = "None"
key_sequence = "+"
[[keymaps]]
command = "VolumeUp"
key_sequence = "="
[[keymaps]]
command = "None"
key_sequence = "q"
[[keymaps]]
command = "ClosePopup"
key_sequence = "q"
[[keymaps]]
command = "Quit"
key_sequence = "Q"
